version: '3.8'

services:
  tax-report-dev-db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_DB: tax-report
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - tax-report-dev-db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  tax-report-dev-db-data:
    driver: local
