version: '3.8'

services:
  postgres-test:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${TRA_POSTGRES_DB}
      POSTGRES_USER: ${TRA_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TRA_POSTGRES_PASSWORD}
    ports:
      - ${TRA_POSTGRES_PORT}:5432
