services:
  tax-report-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: mysql://tax_report:${MYSQL_PASSWORD}@tax-report-mysql:3306/tax_report
      JWT_SECRET: ${JWT_SECRET}
      MEDIA_PATH: /media
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_RECIPIENTS: ${EMAIL_RECIPIENTS}
    depends_on:
      tax-report-mysql:
        condition: service_healthy
    volumes:
      - /opt/tax-report-api/media:/media
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:3000/greeter/greet']
      interval: 5s
      timeout: 5s
      retries: 5

  tax-report-mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tax_report
      MYSQL_USER: tax_report
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - tax_report_mysql:/var/lib/mysql
      - /opt/tax-report-api/backups:/backups:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "tax_report", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  tax-report-mysql-backup:
    image: tiredofit/db-backup:latest
    restart: unless-stopped
    depends_on:
      tax-report-mysql:
        condition: service_healthy
    environment:
      - TZ=America/New_York

      - DB01_TYPE=mysql
      - DB01_HOST=tax-report-mysql
      - DB01_PORT=3306
      - DB01_NAME=tax_report
      - DB01_USER=tax_report
      - DB01_PASS=${MYSQL_PASSWORD}

      - DEFAULT_BACKUP_BEGIN=0 1 * * *
      - DEFAULT_FILESYSTEM_PATH=/backup
      - DEFAULT_CLEANUP_TIME=10080

      - CONTAINER_ENABLE_MONITORING=false
    volumes:
      - /opt/tax-report-api/backups:/backup

volumes:
  tax_report_mysql:
