name: Deploy / Development

on:
  push:
    branches:
      - develop
  pull_request:
    branches: 
      - develop

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  deploy-dev:
    name: Deploy / Development
    needs: build
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Transfer files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TAX_REPORT_HOSTNAME }}
          username: ${{ secrets.TAX_REPORT_SSH_USERNAME }}
          password: ${{ secrets.TAX_REPORT_SSH_PASSWORD }}
          port: ${{ secrets.TAX_REPORT_SSH_PORT }}
          source: ".,!.github"
          target: ${{ secrets.TAX_REPORT_DEPLOY_DIRECTORY }}
          rm: true # Remove target folder before upload data
      
      - name: SSH to server & Deploy app
        uses: appleboy/ssh-action@v1.0.0
        env:
          TAX_REPORT_DEPLOY_DIRECTORY: ${{ secrets.TAX_REPORT_DEPLOY_DIRECTORY }}
        with:
          host: ${{ secrets.TAX_REPORT_HOSTNAME }}
          username: ${{ secrets.TAX_REPORT_SSH_USERNAME }}
          password: ${{ secrets.TAX_REPORT_SSH_PASSWORD }}
          port: ${{ secrets.TAX_REPORT_SSH_PORT }}
          envs: TAX_REPORT_DEPLOY_DIRECTORY
          script: |
            echo "***DEPLOYER***: Change to deploy directory..."
            cd $TAX_REPORT_DEPLOY_DIRECTORY
            
            echo '***DEPLOYER*** Install dependencies'
            npm install

            echo '***DEPLOYER*** Build code'
            npm run build

            echo '***DEPLOYER*** Apply migrations to database'
            npm run migration:deploy:prod

            echo "***DEPLOYER*** Delete running app"
            pm2 delete main

            echo '***DEPLOYER*** Running app'
            pm2 start dist/main.js --name main
