on:
  workflow_call:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.TAX_REPORT_SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.TAX_REPORT_HOSTNAME }}
          REMOTE_USER: ${{ secrets.TAX_REPORT_SSH_USERNAME }}
          TARGET: /home/zhunio-app-tax-report-api/htdocs/tax-report-api.zhunio-app.com
          SCRIPT_AFTER: |
            echo "***DEPLOYER***: Change to deploy directory..."
            cd /home/zhunio-app-tax-report-api/htdocs/tax-report-api.zhunio-app.com
            echo $RSYNC_STDOUT
# echo '***DEPLOYER***: List'
# ls -la

# echo '***DEPLOYER*** Install dependencies'
# npm install

# echo '***DEPLOYER*** Build code'
# npm run build

# echo '***DEPLOYER*** Apply migrations to database'
# npm run migration:deploy:prod

# echo "***DEPLOYER*** Delete running app"
# pm2 delete main

# echo '***DEPLOYER*** Running app'
# pm2 start dist/main.js --name main