name: Deploy / Dev

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [develop]

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Deploy artifact
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.TAX_REPORT_HOSTNAME }}
          username: ${{ secrets.TAX_REPORT_SSH_USERNAME }}
          password: ${{ secrets.TAX_REPORT_SSH_PASSWORD }}
          port: ${{ secrets.TAX_REPORT_SSH_PORT }}
          source: "."
          target: ${{ secrets.TAX_REPORT_DEPLOY_DIRECTORY }}
          rm: true # Remove target folder before upload data
      
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.TAX_REPORT_HOSTNAME }}
          username: ${{ secrets.TAX_REPORT_SSH_USERNAME }}
          password: ${{ secrets.TAX_REPORT_SSH_PASSWORD }}
          port: ${{ secrets.TAX_REPORT_SSH_PORT }}
          script: |
            npm i
            npm run build
            pm2 start dist/main.js
